services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lms
    ports:
      - "3306:3306"
    volumes:
      - lms_mysql_data:/var/lib/mysql

volumes:
  lms_mysql_data:
